import Head from 'next/head'
import { CookPage } from '@home-chefs-org/ui/src/components/templates/CookPage'
import { Container } from '@home-chefs-org/ui/src/components/atoms/Container'

export default function Cook() {
  return (
    <>
      <Head>
        <title>Create cook page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <CookPage />
        </Container>
      </main>
    </>
  )
}
