import { Container } from '@home-chefs-org/ui/src/components/atoms/Container'
import { CustomerPage } from '@home-chefs-org/ui/src/components/templates/CustomerPage'
import Head from 'next/head'

export default function Cook() {
  return (
    <>
      <Head>
        <title>Customer page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <CustomerPage />
        </Container>
      </main>
    </>
  )
}
