import { FormProviderSearchKitchens } from '@home-chefs-org/forms/src/searchKitchens'
import { Container } from '@home-chefs-org/ui/src/components/atoms/Container'
import { IsLoggedIn } from '@home-chefs-org/ui/src/components/organisms/IsLoggedIn'
import { SearchPage } from '@home-chefs-org/ui/src/components/templates/SearchPage'
import Head from 'next/head'

export default function Search() {
  return (
    <>
      <Head>
        <title>Search kitchens | Home chef | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <IsLoggedIn>
            {(uid) => (
              <FormProviderSearchKitchens>
                <SearchPage uid={uid} />
              </FormProviderSearchKitchens>
            )}
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
