import { Container } from '@home-chefs-org/ui/src/components/atoms/Container'
import { IsLoggedIn } from '@home-chefs-org/ui/src/components/organisms/IsLoggedIn'
import { CustomerOrders } from '@home-chefs-org/ui/src/components/templates/CustomerOrders'
import Head from 'next/head'

export default function Orders() {
  return (
    <>
      <Head>
        <title>Orders | Home chefs | Karthick Ragavendran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <IsLoggedIn>
            <CustomerOrders />
          </IsLoggedIn>
        </Container>
      </main>
    </>
  )
}
